version: '3.8'
services:
  ai-animals:
    build:
      context: ./
      target: prod
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
